"""Application-wide constants.

Константы для всего приложения.
"""

# Calculator constants - representation formatting
MAX_SCIENTIFIC_PRECISION = 15
MAX_FRACTION_VALUE = 1000
MAX_FRACTION_DENOMINATOR = 10000
FRACTION_TOLERANCE = 0.0001
MAX_POLAR_PRECISION = 10

# UI dimension constants
LABEL_MIN_WIDTH = 120
INPUT_MIN_WIDTH = 200
PRECISION_GROUP_MIN_WIDTH = 250
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 600

# Precision constants
PRECISION_SLIDER_MIN = 1
PRECISION_SLIDER_MAX = 200
PRECISION_SPINBOX_MIN = 1
PRECISION_SPINBOX_MAX = 1000
PRECISION_SLIDER_TICK_INTERVAL = 20
DEFAULT_PRECISION = 4

# Splitter sizes (result:history ratio)
SPLITTER_RESULT_SIZE = 480
SPLITTER_HISTORY_SIZE = 320

# History display constants
MAX_RESULT_DISPLAY_LENGTH = 20
MAX_HISTORY_ENTRIES = 50
